name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-versions: 2.6.5, 2.7.0, 2.5.7, 2.4.9
    - name: Build and test with Rake
      run: |
        gem install bundler -v '1.11'
        bundle install --jobs 4 --retry 3
        bundle exec rubocop
